// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PearlNecklace;

#nullable disable

namespace PearlNecklace.Migrations
{
    [DbContext(typeof(AddDbContext))]
    [Migration("20220310123513_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PearlNecklace.Necklace", b =>
                {
                    b.Property<int>("necklaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("necklaceID"), 1L, 1);

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("necklaceID");

                    b.ToTable("Necklaces");
                });

            modelBuilder.Entity("PearlNecklace.Pearl", b =>
                {
                    b.Property<int>("pearlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pearlID"), 1L, 1);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("pearlID");

                    b.ToTable("Pearls");
                });
#pragma warning restore 612, 618
        }
    }
}
