// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PearlNecklace;

#nullable disable

namespace PearlNecklace.Migrations
{
    [DbContext(typeof(NecklaceDb))]
    [Migration("20220408090617_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PearlNecklace.Necklace", b =>
                {
                    b.Property<int>("NecklaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NecklaceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NecklaceID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NecklaceName");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("NecklaceID");

                    b.ToTable("Necklaces");
                });

            modelBuilder.Entity("PearlNecklace.Pearl", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("necklaceID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("necklaceID");

                    b.ToTable("Pearls");
                });

            modelBuilder.Entity("PearlNecklace.Pearl", b =>
                {
                    b.HasOne("PearlNecklace.Necklace", null)
                        .WithMany("_pearls")
                        .HasForeignKey("necklaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PearlNecklace.Necklace", b =>
                {
                    b.Navigation("_pearls");
                });
#pragma warning restore 612, 618
        }
    }
}
